pipeline {

    agent any

    stages {

        stage('Clone Code') {

            steps {

                git branch: 'main',

                url: 'https://github.com/mauryavibhav75/attendance-system.git'

            }

        }

        stage('Install Dependencies') {

            steps {

                sh 'pip install --break-system-packages -r requirements.txt'

            }

        }

        stage('Run Tests') {

            steps {

                sh 'python3 -m pytest'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t attendance-system .'

            }

        }

        stage('Deploy Docker Container') {

            steps {

                sh '''

                docker rm -f attendance-app || true

                docker run -d -p 5000:5000 --name attendance-app attendance-system

                '''

            }

        }

    }

}