pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Building project'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing project'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t attendance-app ./backend'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deployment successful'
            }
        }
    }
}