services:
  mongo:
    image: mongo:7
    container_name: attendance-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: attendance-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

volumes:
  mongo-data:
  