pipeline {
    agent any

    environment {
        IMAGE_NAME = "attendance-system"
        CONTAINER_NAME = "attendance-backend"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend') {
                    sh 'npm test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t attendance-system ./backend'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                    docker stop attendance-backend || true
                    docker rm attendance-backend || true
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                    docker run -d \
                      --name attendance-backend \
                      -p 5000:5000 \
                      attendance-system
                '''
            }
        }
    }

    post {
        success {
            echo 'Build and Deployment Successful!'
        }
        failure {
            echo 'Build Failed!'
        }
    }
}