node {

    stage('Checkout') {
        echo "Checking out source code..."
        checkout scm
        sh 'pwd'
        sh 'ls -la'
    }

    stage('Build') {
        echo "Building Project..."
    }

    stage('Run Python') {
        sh 'python3 hello.py'
    }

    stage('Finish') {
        echo "Pipeline Completed Successfully!"
    }
}