pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend Image') {
            steps {
                sh 'docker build -t college-event-backend ./backend'
            }
        }

        stage('Deploy Backend') {
            steps {
                sh 'docker rm -f college-event-backend || true'
                sh 'docker run -d --name college-event-backend --network gitandjiraspratical_college-event-network -p 5000:5000 -e MONGO_URI=mongodb://college-event-mongo:27017/college_event -e PORT=5000 --restart unless-stopped college-event-backend'
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'docker ps'
                sh 'docker logs --tail 30 college-event-backend'
            }
        }
    }

    post {
        success {
            echo 'College Event application deployed successfully!'
        }

        failure {
            echo 'Deployment failed. Check the console output.'
        }
    }
}