// Jenkinsfile
node {

    stage('Checkout') {
        echo "Checking out source code..."
    }

    stage('Build') {
        echo "Building Project"
    }

    stage('Run Python') {
        sh 'python3 hello.py'
    }

    stage('Finish') {
        echo "Pipeline Completed Successfully"
    }

}